import { LineEdit } from "std-widgets.slint";
import { Palette } from "../globals.slint";
import { Icon } from "Icon.slint";

export component ModernLineEdit inherits Rectangle {
    in property <string> placeholder-text;
    in property <bool> has-focus: input.has-focus;
    out property <string> text <=> input.text;
    callback accepted(string);
    callback edited(string);
    height: 45px;
    background: Palette.current.surface_color;
    border-radius: 12px;
    border-width: 1px;
    border-color: input.has-focus ? Palette.current.accent_color : Palette.current.border_color;
    animate border-color { duration: 200ms; }
    HorizontalLayout {
        padding-left: 16px;
        padding-right: 16px;
        spacing: 12px;
        Icon {
            icon_name: "search";
            size: 18px;
            icon_color: Palette.current.text_secondary;
        }

        input := LineEdit {
            width: 100%;
            height: 100%;
            placeholder-text: root.placeholder-text;
            font-size: 14px;
            accepted => {
                root.accepted(self.text);
            }
            edited => {
                root.edited(self.text);
            }
        }
    }
}
