import { Palette } from "../globals.slint";
import { Icon } from "Icon.slint";

export component SidebarButton inherits Rectangle {
    in property <string> text;
    in property <string> icon;
    in property <bool> active: false;
    in property <bool> collapsed: false;
    callback clicked <=> touch.clicked;
    height: 40px;
    border-radius: 8px;
    background: root.active ? Palette.current.surface_color : (touch.has-hover ? Palette.current.surface_color.darker(5%) : transparent);
    animate background { duration: 200ms; }
    touch := TouchArea { }

    HorizontalLayout {
        padding-left: 12px;
        padding-right: 12px;
        spacing: 12px;
        alignment: start;
        Icon {
            icon_name: root.icon;
            size: 18px;
            icon_color: root.active ? Palette.current.accent_color : Palette.current.text_secondary;
            y: (parent.height - self.height) / 2;
        }

        if !root.collapsed: Text {
            text: root.text;
            font-size: 14px;
            font-weight: root.active ? 600 : 400;
            color: root.active ? Palette.current.text_primary : Palette.current.text_secondary;
            vertical-alignment: center;
        }
    }
}
