import { Palette } from "../globals.slint";
import { Icon } from "Icon.slint";

export component ThemeToggle inherits Rectangle {
    callback toggled;
    width: 40px;
    height: 40px;
    border-radius: 20px;
    background: touch.has-hover ? Palette.current.surface_color : transparent;
    animate background { duration: 200ms; }
    touch := TouchArea {
        clicked => {
            root.toggled();
        }
    }

    Icon {
        icon_name: Palette.is_dark ? "moon" : "sun";
        size: 20px;
        icon_color: Palette.is_dark ? #fcd34d : #f59e0b; // Yellowish for sun/moon
        x: (parent.width - self.width) / 2;
        y: (parent.height - self.height) / 2;
    }
}
